catalog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.index, name="index"),
    path("books", views.BookListView.as_view(), name="books"),
    path("book/<int:pk>", views.BookDetailView.as_view(), name="book"),
    path("authors", views.AuthorListView.as_view(), name="authors"),
    path("author/<int:pk>", views.AuthorDetailView.as_view(), name="author"),
]

testproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
    path("", RedirectView.as_view(url="catalog/")),
    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
]

catalog/models.py
from django.db import models
import uuid


# Create your models here.


class Author(models.Model):
    name = models.CharField(
        max_length=100,
        null=False,
        help_text="An author's full name. (Example: W. Shakespear or Mihail Afanasievich Bulgakov)",
    )
    date_of_birth = models.DateField(
        null=True,
        blank=True,
        help_text="A date of author's birth (or Null, if unknown).",
    )
    date_of_death = models.DateField(
        null=True,
        blank=True,
        help_text="A date of author's death (or Null, if alive or unknown)."
    )

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return f"/catalog/author/{self.pk}"


class Genre(models.Model):
    name = models.CharField(
        max_length=100, help_text="A book genre. (example: Science Fiction)"
    )

    def __str__(self) -> str:
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    summary = models.TextField()
    language = models.CharField(max_length=100)
    author = models.ForeignKey(Author, null=True, on_delete=models.SET_NULL)
    genres = models.ManyToManyField(Genre)

    def __str__(self) -> str:
        return f"{self.author.name} - {self.title!r}"

    def get_absolute_url(self) -> str:
        return f"/catalog/book/{self.pk}"


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    imprint = models.CharField(max_length=100)
    year = models.SmallIntegerField()
    book = models.ForeignKey(Book, null=False, on_delete=models.CASCADE)

    LOAN_STATUS = (
        ("o", "On loan"),
        ("a", "Available"),
        ("r", "Reserved"),
    )

    status = models.CharField(
        max_length=1, choices=LOAN_STATUS, default="a", null=False
    )
    due_back = models.DateField(null=True, blank=True)

    def __str__(self) -> str:
        return f"{str(self.id)[:8]} ({self.book})"

    def get_display_status(self) -> str:
        return dict(self.LOAN_STATUS)[self.status] + (
            "" if self.status != "o" else f" until {self.due_back}"
        )

catalog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Book, Author, BookInstance, Genre
from typing import Any

# Create your views here.


class BookListView(generic.ListView):
    model = Book
    context_object_name = "book_list"
    queryset = Book.objects.all()
    template_name = "book/list.html"

    # def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
    #     return super().get_context_data(**kwargs) | {"book_list": Book.objects.all()}


class BookDetailView(generic.DetailView):
    model = Book
    template_name = "book/detail.html"


class AuthorListView(generic.ListView):
    model = Author
    context_object_name = "author_list"
    queryset = Author.objects.all()
    template_name = "author/list.html"


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = "author/detail.html"


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact="a").count()
    num_authors = Author.objects.all().count()

    return render(
        request,
        "index.html",
        context={
            "num_books": num_books,
            "num_instances": num_instances,
            "num_instances_available": num_instances_available,
            "num_authors": num_authors,
        },
    )

catalog/templates/author/detail.html
{% extends "base_generic.html" %} {% block content %}

<h1>Title: {{object.name}}</h1>

<p><strong>Date of Birth:</strong> {{ object.date_of_birth }}</p>
<p><strong>Date of Death:</strong> {{ object.date_of_death }}</p>
<p>
    <strong>Books:</strong>
    {% for book in object.books.all %} {{ book }}{% if not forloop.last %}, {%endif%} {% endfor %}
</p>

{% endblock %}

catalog/templates/author/list.html
{% extends "base_generic.html" %} {% block content %}

<h1>Author list</h1>

{% if author_list %}

<ul>
    {% for author in author_list %}
    <li><a href="{{ author.get_absolute_url }}"> {{ author.name }}</a></li>
    {% endfor %}
</ul>

{% else %}

<p>There are no authors:c</p>

{% endif %} {% endblock %}

catalog/templates/base_generic.html
<!DOCTYPE html>
<html>
    <head>
        {% block title %}
        <title>Local Library</title>
        {% endblock %}

        <!-- Latest compiled and minified CSS -->
        <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
            integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
            crossorigin="anonymous"
        />

        <!-- Optional theme -->
        <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
            integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
            crossorigin="anonymous"
        />

        <!-- Jquery -->
        <script
            src="https://code.jquery.com/jquery-1.12.4.js"
            integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
            crossorigin="anonymous"
        ></script>

        <!-- Latest compiled and minified JavaScript -->
        <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"
        ></script>

        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {% block sidebar %}
                    <ul class="sidebar-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'books' %}">All books</a></li>
                        <li><a href="{% url 'authors' %}">All authors</a></li>
                    </ul>
                    {% endblock %}
                </div>
                <div class="col-sm-10">
                    {% block content %}
                    <!-- default content-->
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

catalog/templates/book/detail.html
{% extends "base_generic.html" %} {% block content %}

<h1>Title: {{object.title}}</h1>

<p><strong>Author:</strong> {{ object.author }}</p>
<p><strong>Summary:</strong> {{ object.summary }}</p>
<p>
    <strong>Genres:</strong>
    {% for genre in object.genres.all %} {{ genre }}{% if not forloop.last %}, {%endif%} {% endfor %}
</p>
<p><strong>Language:</strong> {{ object.language }}</p>

<div style="margin-top: 60px">
    <h4>Copies</h4>

    {% for copy in object.bookinstance_set.all %}
    <hr />
    <p
        class="{% if copy.status == 'a'%}text-success{% elif copy.status == 'o' %}text-danger{% else %}text-warning{% endif %}"
    >
        {{copy.get_display_status}}
    </p>
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p><strong>Year:</strong> {{copy.year}}</p>
    <p class="text-muted"><strong>ID:</strong> {{copy.id}}</p>

    {% endfor %}
</div>

{% endblock %}

catalog/templates/book/list.html
{% extends "base_generic.html" %} {% block content %}

<h1>Book list</h1>

{% if book_list %}

<ul>
    {% for book in book_list %}
    <li><a href="{{ book.get_absolute_url }}"> {{ book.title }}</a> {{ book.author }}</li>
    {% endfor %}
</ul>

{% else %}

<p>There are no books :c</p>

{% endif %} {% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %} {% block content %}
<h1>Welcome to library!</h1>
<p>Welcome to <em>LocalLibrary</em>, a web application made on Django Framework</p>

<h2>Dynamic data</h2>
<ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Book instances:</strong> {{ num_instances }}</li>
    <li><strong>Book instances (available):</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
</ul>
{% endblock %}